version: '3.5'

services:
#--------------------------------
  nginxBot:
    container_name: nginxBot_cont
    image: nginx:1.25.5-perl
    env_file:
      - DockerEnv.env
#    environment:
#      - NGINX_HOST=bot.z2024.site
#      - NGINX_PORT=88
#      - WEBHOOK_PORT=8444
#      - REDIRECT_URL=172.100.0.5
    volumes:
      - conf:/etc/nginx
    ports:
      - "${WEBHOOK_PORT:-8443}:80"
    networks:
      net1:
        ipv4_address: 172.100.0.2
    restart: unless-stopped

#------------------------------
networks:
  net1:
    driver: bridge
    ipam:
     config:
       - subnet: 172.100.0.0/24
         gateway: 172.100.0.1
#------------------------------
volumes:
  conf:

# ====================
        #      - ./sites-available:/etc/nginx/sites-available
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - sites-available: /etc/nginx/sites-available
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /etc/nginx/
#      - postgres:/data/postgres

  #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #      POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #      PGDATA: /data/postgres

  #      sites-available:
#    postgres:
#    adminer:
#    pgadmin:

